name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set and install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq make gcc gettext autoconf automake autopoint autotools-dev pkg-config gobject-introspection libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtk-3-dev libinstpatch-dev libsndfile-dev libsamplerate-dev libsoup2.4-dev libxml2-dev ladspa-sdk dssi-dev lv2-dev fftw3-dev libasound2-dev libjack-jackd2-dev libpulse-dev uuid-dev xvfb libcunit1-dev gtk-doc-tools
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure
    - name: update-po
      run: make update-po
    - name: make
      run: make
    - name: make check
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a make check
    - name: make distcheck
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a make distcheck
