name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set and install dependencies
      run: |
        sudo apt-get update -qq 
	sudo apt-get install -qq make gcc gettext autoconf automake autopoint pkg-config libgtk2.0-dev libinstpatch-dev libsndfile-dev libsamplerate-dev libxml2-dev ladspa-sdk dssi-dev lv2-dev fftw3-dev libasound2-dev libjack-jackd2-dev libpulse-dev uuid-dev libcunit1-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
